<DumpingScreen>:

    ScrollView:

        GridLayout:
            cols: 1
            spacing: 15
            padding: 20

            size_hint_y: None
            height: self.minimum_height

            Label:
                text: "DUMPING PARTY"
                font_size: "30sp"

                size_hint_y: None
                height: 60

# ---------------- DUMPING ----------------

            Label:
                text: "MINES DUMPED"

                size_hint_y: None
                height: 40

            Label:
                text: root.dumping

                size_hint_y: None
                height: 60

                canvas.before:
                    Color:
                        rgba:
                            (0,1,0,1) if root.dumping=="GREEN" else \
                            (1,0.5,0,1) if root.dumping=="ORANGE" else \
                            (1,0,0,1)

                    Rectangle:
                        pos: self.pos
                        size: self.size

            BoxLayout:

                size_hint_y: None
                height: 60

                Button:
                    text: "RED"

                    on_release:
                        root.set_status("RED")

                Button:
                    text: "ORANGE"

                    on_release:
                        root.set_status("ORANGE")

                Button:
                    text: "GREEN"

                    on_release:
                        root.set_status("GREEN")

# ---------------- GRID REF ----------------

            Label:
                text: "GRID REFERENCE"

                size_hint_y: None
                height: 40

            TextInput:
                id: grid_input
                hint_text: "Enter Grid Ref"

                size_hint_y: None
                height: 50

            Button:
                text: "UPDATE GRID"

                size_hint_y: None
                height: 60

                on_release:
                    root.set_grid()

            Label:
                text: "Current Grid : " + root.grid

                size_hint_y: None
                height: 50

# ---------------- SOS ----------------

            Button:
                text: "🚨 SOS"

                size_hint_y: None
                height: 60

                on_release:
                    root.send_sos()

# ---------------- LOGOUT ----------------

            Button:
                text: "LOGOUT"

                size_hint_y: None
                height: 60

                on_release:
                    root.logout()