<LoginScreen>:

    BoxLayout:

        orientation: "vertical"
        spacing: 15
        padding: 30

        canvas.before:
            Color:
                rgba: 0.08,0.08,0.08,1

            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "BATTLEFIELD TRACKER"
            font_size: "32sp"

        Label:
            text: "LOGIN"
            font_size: "22sp"

        TextInput:
            id: username
            hint_text: "Username"

        TextInput:
            id: password
            hint_text: "Password"
            password: True

        Button:
            text: "LOGIN"
            size_hint_y: .25
            on_release: root.login()

        Label:
            id: message
            text: ""